# provision.py - WiFi AP mode provisioning
# Creates a hotspot + captive portal for WiFi setup

import network
import socket
import time
import os

AP_SSID = "Cistern-Setup"
AP_PASSWORD = "cistern123"
CONFIG_FILE = "config.py"

SETUP_PAGE = """<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cistern Setup</title>
    <style>
        body { font-family: -apple-system, sans-serif; max-width: 400px; margin: 40px auto; padding: 0 20px; background: #1a1a2e; color: #eee; }
        h1 { color: #0f3460; background: #e94560; padding: 12px; border-radius: 8px; text-align: center; }
        label { display: block; margin-top: 16px; font-weight: bold; }
        input { width: 100%; padding: 10px; margin-top: 4px; border: 1px solid #444; border-radius: 6px; box-sizing: border-box; font-size: 16px; background: #16213e; color: #eee; }
        button { width: 100%; padding: 12px; margin-top: 24px; background: #e94560; color: #fff; border: none; border-radius: 6px; font-size: 18px; cursor: pointer; }
        button:hover { background: #c73650; }
        .status { text-align: center; margin-top: 16px; color: #aaa; }
    </style>
</head>
<body>
    <h1>Cistern Monitor</h1>
    <form method="POST" action="/save">
        <label>WiFi Network Name</label>
        <input type="text" name="ssid" required>
        <label>WiFi Password</label>
        <input type="password" name="password" required>
        <button type="submit">Save & Connect</button>
    </form>
    <p class="status">Connect to your WiFi to start monitoring</p>
</body>
</html>"""

SUCCESS_PAGE = """<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cistern Setup</title>
    <style>
        body { font-family: -apple-system, sans-serif; max-width: 400px; margin: 40px auto; padding: 0 20px; background: #1a1a2e; color: #eee; text-align: center; }
        h1 { color: #0f3460; background: #0ead69; padding: 12px; border-radius: 8px; }
        p { font-size: 18px; }
    </style>
</head>
<body>
    <h1>Saved!</h1>
    <p>Connecting to <strong>{ssid}</strong>...</p>
    <p>The device will reboot in a few seconds.</p>
    <p>You can close this page and reconnect to your WiFi.</p>
</body>
</html>"""


def has_config():
    """Check if WiFi config already exists"""
    try:
        from config import WIFI_SSID, WIFI_PASSWORD
        return bool(WIFI_SSID and WIFI_SSID != "your_wifi_name")
    except (ImportError, AttributeError):
        return False


def save_config(ssid, password):
    """Save WiFi credentials to config.py"""
    # Read existing config if it exists
    existing = {}
    try:
        with open(CONFIG_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, val = line.split('=', 1)
                    existing[key.strip()] = val.strip()
    except:
        pass

    # Update WiFi creds
    existing['WIFI_SSID'] = f'"{ssid}"'
    existing['WIFI_PASSWORD'] = f'"{password}"'

    # Set defaults if missing
    if 'OTA_BASE_URL' not in existing:
        existing['OTA_BASE_URL'] = '""'
    if 'OTA_FILES' not in existing:
        existing['OTA_FILES'] = "['main.py', 'sensor.py', 'ota.py', 'firebase.py']"
    if 'FIREBASE_PROJECT_ID' not in existing:
        existing['FIREBASE_PROJECT_ID'] = '""'
    if 'FIREBASE_API_KEY' not in existing:
        existing['FIREBASE_API_KEY'] = '""'

    with open(CONFIG_FILE, 'w') as f:
        f.write("# config.py - Auto-generated by provisioning\n")
        for key, val in existing.items():
            f.write(f"{key} = {val}\n")

    print(f"Config saved: SSID={ssid}")


def parse_form(body):
    """Parse URL-encoded form data"""
    params = {}
    for pair in body.split('&'):
        if '=' in pair:
            key, val = pair.split('=', 1)
            # URL decode
            val = val.replace('+', ' ')
            val = val.replace('%21', '!').replace('%40', '@')
            val = val.replace('%23', '#').replace('%24', '$')
            val = val.replace('%25', '%').replace('%26', '&')
            val = val.replace('%3D', '=').replace('%3F', '?')
            params[key] = val
    return params


def start_ap():
    """Start the access point"""
    ap = network.WLAN(network.AP_IF)
    ap.active(True)
    ap.config(essid=AP_SSID, password=AP_PASSWORD)

    # Wait for AP to be active
    while not ap.active():
        time.sleep(0.1)

    print(f"AP started: {AP_SSID}")
    print(f"AP password: {AP_PASSWORD}")
    print(f"IP: {ap.ifconfig()[0]}")
    return ap


def run_server():
    """Run the provisioning captive portal"""
    from machine import Pin
    led = Pin('LED', Pin.OUT)

    ap = start_ap()
    ip = ap.ifconfig()[0]

    server = socket.socket()
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind(('0.0.0.0', 80))
    server.listen(1)

    print(f"Provisioning server at http://{ip}")

    # Blink LED rapidly to indicate setup mode
    led.on()

    while True:
        try:
            conn, addr = server.accept()
            request = conn.recv(1024).decode()

            if 'POST /save' in request:
                # Extract body
                body = request.split('\r\n\r\n', 1)[-1]
                params = parse_form(body)

                ssid = params.get('ssid', '')
                password = params.get('password', '')

                if ssid:
                    # Send success page
                    response = SUCCESS_PAGE.format(ssid=ssid)
                    conn.send("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n")
                    conn.send(response)
                    conn.close()

                    # Save and reboot
                    save_config(ssid, password)
                    time.sleep(2)

                    ap.active(False)
                    import machine
                    machine.reset()
                else:
                    conn.send("HTTP/1.1 400 Bad Request\r\n\r\nMissing SSID")
                    conn.close()
            else:
                # Serve setup page for any GET request (captive portal)
                conn.send("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n")
                conn.send(SETUP_PAGE)
                conn.close()

        except Exception as e:
            print(f"Server error: {e}")
            try:
                conn.close()
            except:
                pass
