# provision.py - WiFi AP mode provisioning
# Single-threaded captive portal: DNS + HTTP via select.poll()

import network
import socket
import select
import time
import os

AP_SSID = "Cistern-Setup"
AP_PASSWORD = "cistern123"
CONFIG_FILE = "config.py"

SETUP_PAGE = (
    "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: close\r\n\r\n"
    "<!DOCTYPE html><html><head>"
    '<meta name="viewport" content="width=device-width,initial-scale=1">'
    "<title>Cistern Setup</title><style>"
    "body{font-family:sans-serif;max-width:380px;margin:40px auto;padding:0 16px;background:#1a1a2e;color:#eee}"
    "h1{background:#e94560;padding:10px;border-radius:8px;text-align:center}"
    "label{display:block;margin-top:14px;font-weight:bold}"
    "input{width:100%;padding:8px;margin-top:4px;border:1px solid #444;border-radius:6px;"
    "box-sizing:border-box;font-size:16px;background:#16213e;color:#eee}"
    "button{width:100%;padding:10px;margin-top:20px;background:#e94560;color:#fff;"
    "border:none;border-radius:6px;font-size:18px}"
    "</style></head><body><h1>Cistern Monitor</h1>"
    '<form method="POST" action="/save">'
    "<label>WiFi Name</label>"
    '<input name="ssid" required>'
    "<label>WiFi Password</label>"
    '<input type="password" name="password" required>'
    "<button type=\"submit\">Save &amp; Connect</button>"
    "</form></body></html>"
)

SUCCESS_TMPL = (
    "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: close\r\n\r\n"
    "<!DOCTYPE html><html><head>"
    '<meta name="viewport" content="width=device-width,initial-scale=1">'
    "<title>Saved</title><style>"
    "body{font-family:sans-serif;max-width:380px;margin:40px auto;padding:0 16px;"
    "background:#1a1a2e;color:#eee;text-align:center}"
    "h1{background:#0ead69;padding:10px;border-radius:8px}"
    "</style></head><body><h1>Saved!</h1>"
    "<p>Connecting to <strong>{ssid}</strong>...</p>"
    "<p>Device will reboot. Reconnect to your WiFi.</p>"
    "</body></html>"
)


def has_config():
    try:
        from config import WIFI_SSID, WIFI_PASSWORD
        return bool(WIFI_SSID and WIFI_SSID != "your_wifi_name")
    except (ImportError, AttributeError):
        return False


def save_config(ssid, password):
    existing = {}
    try:
        with open(CONFIG_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, val = line.split('=', 1)
                    existing[key.strip()] = val.strip()
    except:
        pass

    existing['WIFI_SSID'] = '"{}"'.format(ssid)
    existing['WIFI_PASSWORD'] = '"{}"'.format(password)

    if 'OTA_BASE_URL' not in existing:
        existing['OTA_BASE_URL'] = '"https://raw.githubusercontent.com/bosmun0224/cistern/main/"'
    if 'OTA_FILES' not in existing:
        existing['OTA_FILES'] = "['main.py', 'sensor.py', 'ota.py', 'firebase.py']"
    if 'FIREBASE_PROJECT_ID' not in existing:
        existing['FIREBASE_PROJECT_ID'] = '"cistern-blomquist"'
    if 'FIREBASE_API_KEY' not in existing:
        existing['FIREBASE_API_KEY'] = '"AIzaSyCMvUgbaUvekblMsrPx7Pg9sPrmgB4iPk4"'

    with open(CONFIG_FILE, 'w') as f:
        f.write("# config.py - Auto-generated by provisioning\n")
        for key, val in existing.items():
            f.write("{} = {}\n".format(key, val))
    print("Config saved: SSID=" + ssid)


def parse_form(body):
    params = {}
    for pair in body.split('&'):
        if '=' in pair:
            key, val = pair.split('=', 1)
            val = val.replace('+', ' ')
            val = val.replace('%21', '!').replace('%40', '@')
            val = val.replace('%23', '#').replace('%24', '$')
            val = val.replace('%25', '%').replace('%26', '&')
            val = val.replace('%3D', '=').replace('%3F', '?')
            params[key] = val
    return params


def start_ap():
    ap = network.WLAN(network.AP_IF)
    ap.active(True)
    time.sleep(0.5)
    # Use WPA2 constant — older MicroPython used security=4, v1.28+ uses SEC_WPA2
    try:
        sec = network.WLAN.SEC_WPA2
    except AttributeError:
        sec = 4
    ap.config(ssid=AP_SSID, key=AP_PASSWORD, security=sec)
    print("AP started: " + ap.config('ssid'))
    print("IP: " + ap.ifconfig()[0])
    return ap


def _dns_reply(data, ip_bytes):
    """Build a DNS A-record response pointing all queries to our AP IP."""
    # Header: copy txn ID, set response flags, 1 question, 1 answer
    resp = data[:2] + b'\x81\x80'
    resp += b'\x00\x01\x00\x01\x00\x00\x00\x00'
    # Copy the question section verbatim
    qend = 12
    while data[qend] != 0:
        qend += data[qend] + 1
    qend += 5  # null terminator + qtype(2) + qclass(2)
    resp += data[12:qend]
    # Answer: name pointer, type A, class IN, TTL 60, 4-byte IP
    resp += b'\xc0\x0c\x00\x01\x00\x01\x00\x00\x00\x3c\x00\x04'
    resp += ip_bytes
    return resp


def run_server():
    """Single-threaded DNS + HTTP captive portal using select.poll().

    DNS redirects every domain lookup to the AP IP so phones/tablets
    auto-detect the captive portal and pop up the setup page.
    USB REPL stays accessible via sys.stdin polling.
    """
    import sys
    from machine import Pin

    led = Pin('LED', Pin.OUT)
    ap = start_ap()
    ip = ap.ifconfig()[0]
    ip_bytes = bytes(int(b) for b in ip.split('.'))

    # --- HTTP (TCP) ---
    http = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    http.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    http.bind(('0.0.0.0', 80))
    http.listen(2)

    # --- DNS (UDP) ---
    dns = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    dns.bind(('0.0.0.0', 53))

    poller = select.poll()
    poller.register(http, select.POLLIN)
    poller.register(dns, select.POLLIN)
    # Poll USB stdin so REPL Ctrl+C can interrupt
    poller.register(sys.stdin, select.POLLIN)

    print("Captive portal ready at http://" + ip)
    led.on()

    while True:
        for sock, ev in poller.poll(1000):
            try:
                if sock is sys.stdin:
                    # Let MicroPython handle USB input (Ctrl+C will raise KeyboardInterrupt)
                    char = sys.stdin.read(1)
                    if char == '\x03':  # Ctrl+C
                        raise KeyboardInterrupt

                elif sock is dns:
                    data, addr = dns.recvfrom(256)
                    if len(data) > 12:
                        dns.sendto(_dns_reply(data, ip_bytes), addr)

                elif sock is http:
                    conn, addr = http.accept()
                    try:
                        request = conn.recv(1024).decode()

                        if 'POST /save' in request:
                            body = request.split('\r\n\r\n', 1)[-1]
                            params = parse_form(body)
                            ssid = params.get('ssid', '')
                            password = params.get('password', '')

                            if ssid:
                                conn.send(SUCCESS_TMPL.format(ssid=ssid))
                                conn.close()
                                save_config(ssid, password)
                                time.sleep(2)
                                ap.active(False)
                                import machine
                                machine.reset()
                            else:
                                conn.send("HTTP/1.1 400 Bad Request\r\n\r\nMissing SSID")
                                conn.close()
                        else:
                            # Serve setup page for ANY request (captive portal detect + manual)
                            conn.send(SETUP_PAGE)
                            conn.close()
                    except Exception as e:
                        print("HTTP error: " + str(e))
                        try:
                            conn.close()
                        except:
                            pass

            except KeyboardInterrupt:
                print("\n*** Ctrl+C — dropping to REPL ***")
                print("Portal stopped. Run import machine; machine.reset() to restart.")
                led.off()
                http.close()
                dns.close()
                return

            except Exception as e:
                print("Poll error: " + str(e))
